# To release:
# git tag -a v1.0.0 -m "Version 1.0.0"
# git push origin v1.0.0

name: Zip and release the Vale package.

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version (for example, v1.2.3)"
        required: true

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out the repository.
        uses: actions/checkout@v4

      - name: 2. Prepare the package.
        run: |
          mkdir -p release/christian-vale
          cp -R styles release/christian-vale/

      - name: 3. Zip the package.
        working-directory: release
        run: zip -r christian-vale.zip christian-vale

      - name: 4. Upload the package.
        uses: actions/upload-artifact@v4
        with:
          name: christian-vale
          path: release/christian-vale.zip

      - name: 5. Set the release version.
        id: set-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]
          then
            echo "tag_name=${{ github.event.inputs.release-version }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "push" ]
          then
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "Error: Event type not supported."
            exit 1
          fi

      - name: 6. Release the package.
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set-version.outputs.tag_name }}
          files: release/christian-vale.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 6. Clean up.
        run: rm -rf release
