name: Package and release christian-vale

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version (for example, 1.0.1)"
        required: true

permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    if: |
      '
        (
          github.event.pull_request.base.ref == "main" &&
          github.event_name == "pull_request" &&
          github.event.pull_request.merged == true
        ) ||
        github.event_name == "workflow_dispatch"
      '

    steps:
      - name: 1. Check out the main branch.
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: 2. Set the release version.
        id: set-release-version
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]
          then
            RELEASE_VERSION=$(cat VERSION)
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]
          then
            RELEASE_VERSION=${{ github.event.inputs.release-version }}
          else
            echo "Error: The workflow doesn’t support your event type."
            exit 1
          fi
          echo "release-version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT

      - name: 3. Prepare the package.
        run: |
          mkdir -p release/christian-vale
          cp -R src/styles release/christian-vale/

      - name: 4. Zip the package.
        working-directory: release
        run: zip -r christian-vale.zip christian-vale

      - name: 5. Upload the package.
        uses: actions/upload-artifact@v4
        with:
          name: christian-vale
          path: release/christian-vale.zip

      - name: 6. Release the package.
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.set-release-version.outputs.release-version }}
          files: release/christian-vale.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 7. Clean up.
        run: rm -rf release
